### ISSUE TITLE
status update for the 'mine' example app?

### ISSUE THREAD

**Issue by jdmairs** [mmikowski/hi_score#12]
Mid 2019 is what I read in the README...any updates?  We would really like to see a LOB type app.

**Comment by mmikowski** [comment]
Thank you for your interest. Please help me understand what you are looking for? At present, we have typebomb2 which is a non-trivial app, and I was thinking of adding an express backend. Also, I need to update typebomb2 to the latest capabilities which should significantly reduce the code base and the reliance on jQuery.  I am very open to suggestions on how to proceed.

**Comment by jdmairs** [comment]
Hi Mike,

Thanks for getting back to me.  I've included my project lead on this
email.

Dave and I's background is C++ systems programming.  I wrote our first
webapp 3 years ago based solely on your SPA book.  We are now ramping up
for our 2nd app and are evaluating various tech stacks.  Basically it comes
down to hi_score vs react and redux.  We are getting a lot of team pressure
from our younger devs (that have more web app experience then us) that
React is a silver bullet and that no one uses/knows jQuery anymore.  Our
app will be looking at 10k records in a list tool control with
synchronization to a map control and we wonder if we can work directly with
the DOM or will react's virtual dom do the double buffering and any other
low level stuff.

In the SPA book I loved the following architecture/design decisions you
made:

   1. feature/module approach
   2. separate data access layer from data model layer
   3. web sockets with pub/sub between client and server
   4. jQuery events for pub/sub between the various layers on client side

I felt embedding the html frames as strings in the .js features was a bit
cumbersome.  As I peruse the SPA book again I see you had some VIM features
that help with that.


I've just begun to go over the typebomb2 app and thankfully it feels
familiar yet more structured and polished at the same time.

One thing we both puzzle over is all the abstraction that is needed.  Stuff
like this in 07_shell

// Set app symbols
aMap = tb02,
aKey = aMap._aKey_,
nMap = aMap._nMap_,
vMap = aMap._vMap_ I recognize/remember application state and configuration
state in the SPA book but wonder what these other maps are for.

I read how the author of nodeunit suggests you use something else like
jest.  Would you be open to pull requests that replace nodeunit with jest
in hi_score?

Most of your unit testing in hi_score is around the xhi build kit.  I
didn't see much if any around the domain logic of typebomb2.

Thanks for your time and putting up with this rambling email.

John

**Comment by mmikowski** [comment]
Hi John:

Thanks for your interest and I appreciate your kind words on TypeBomb2. When I bring it up to date to latest standards I think it will be more impressive.

As for the embedded strings, yes, I have a vim macro which does this for me in standard VIM or ideavim. From my .vimrc:

```
" ;q Format selection for JS string, ;h undoes
vmap <silent> ;q :s?^\(\s*\)\(.*\)\s*$?      + \1'\2'?<CR>
vmap <silent> ;h :s?^\(\s*\)+\(\s*\)'\([^']\+\)',*\s*$?\1\2\3?g<CR>
```
While I am enticed by the promise of JSX, my experience with Vue is that all the abstraction and trans-piling magic that has to happen simply doesn't make it worth it.  Yes, managing the strings is a bit of a PITA, but it pales in comparison to trying to debug a Vue app with JSX in my experience. There is no magic, and bugs are much easier to find.

**Yes I would love a pull request moving from nodeunit to Jest!** I continue to use nodeunit because it works even though it is deprecated.

The aMap is the application map. I've abstracted that to make code more portal. Say you change your namespace from tb02 to tb03. Then the entire application can be updated to this namespace in a single declaration:
```
aMap = tb03
```
The nMap and vMap values are root symbol maps and are optional optimization. The libraries define most symbols and numbers only once in the entire code base. The apps I've been pushing to client benefit from obfuscation and size reduction. I use IntelliJ which really helps with this use - I can easily see that I have a symbol like `vMap._hasOwnProperty_` through introspection. When compressed this is much shorter than the actual property name, e.g. `x0.ai`.

And yes you are right, I need to add regression tests for Typebomb. The good new it is test-ready thanks to it's architecture and the libraries around it. I also want to split up the tests in test.d.

I have spent months with both VueJS and Angular, and have worked with React (and Closure, Backbone, and other tools time forgot). I believe hi_score is a superior choice for experience developers thanks to extensive full-life-cycle support, build-for-test architecture, simplicity, and transparency. 

Cheers, Mike
