### ISSUE TITLE
status update for edition 2 of the SPA book?

### ISSUE THREAD

**Issue by jdmairs** [mmikowski/hi_score#13]
Understand that the publisher rules the day...any chance of a +- 3 months or so?

**Comment by mmikowski** [comment]
@jdmairs I am looking to reignite the book which I had to put aside in 2018 for various reasons but am returning in the later half of this year.  I have the first 3 or 4 chapters and 3 appendices written. Would you like to review?

**Comment by jdmairs** [comment]
Absolutely would like to review.

**Comment by lwhite1** [comment]
Will the new edition be based on Hi-Score? I'm trying to understand whether to:

- develop based on the first edition, on Hi-Score?, or on something "safe" (i.e., better known, if not as good).

- continue reading the first edition as an intro to working with Hi-Score. I sense a family resemblance, but I'm not sure if the differences and library updates would make that a pointless exercise

**Comment by mmikowski** [comment]
Hi Jd:
The book was set aside due to me joining a company with a insane push for constant push for 110% commitment. Worst job of my life. Due to the delays (and the groupthink at Manning) they withdrew from publication. 
I recently quit the slave-job and am working on a hardware project. However, I believe the hi_score framework is far the best approach available for developing web apps. If the book were to come out tomorrow it would be about the automatons employed in hi_score. It has been used for highly visible demonstration and production systems for the likes of Walmart, PG&E, WeWork, Amazon, MacAfee, and other large companies.  I am in the process of writing a generator currently so that adding a new app take seconds.
At this point, expect all the docs for v2 to end up in hi_score, and hi_score is effectively the v2 of the book.
Cheers, Mike

    On Friday, November 1, 2019, 09:00:54 AM PDT, Larry White <notifications@github.com> wrote:  
 
 
Will the new edition be based on Hi-Score? I'm trying to understand whether to:
   
   -    
develop based on the first edition, on Hi-Score?, or on something "safe" (i.e., better known, if not as good).

   -    
continue reading the first edition as an intro to working with Hi-Score. I sense a family resemblance, but I'm not sure if the differences and library updates would make that a pointless exercise
