### ISSUE TITLE
is his_score being maintained in 2019?

### ISSUE THREAD

**Issue by jdmairs** [mmikowski/hi_score#8]
I absolutely loved your SPA book.  I used the concepts in my first web app.  I downloaded the ova appliance and have started the tutorial/docs.  I'm noticing lots of deprecated warnings doing the git clone and the repo hasn't been updated in a long time.

Are you too busy or is this concept overtaken by other technologies?

Thanks!

**Comment by mmikowski** [comment]
Jdmairs, I am actively using hi_score on multiple production products and will soon be releasing a 1.5 version with many enhancements and a library upgrades.  The last year has been very busy, but I am now getting some time to get this back on track.

After the 1.5 expect a new virtual appliance based on Ubuntu 19.04. Other things in the works include v2 of the book which will emphasize Hi_score, PowerCss, and techniques such as [TypeCasting](https://mmikowski.github.io/typecast-02/).  I am also moving a pub/sub system to the 03_model.js instance.  Also look for automatic culling of unused functions on compression and enhanced websocket support in the 1.5 plans.

So this is very much active and IMO, superior to using React / Vue / Angular. I prefer it because it doesn't use Babble and it has full life-cycle support with a strong emphasis on TDD.  It also embraces using best-in-class libraries.

**Comment by mmikowski** [comment]
Closing. Look for a 1.5 update this week.
